# https://makeeyaf.postype.com/post/8614009
name: Link Jira issue key in PR

on: 
  pull_request:
    types: [opened]

jobs:
  link_jira_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Jira Login
        uses: atlassian/gajira-login@v2.0.0
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Find Jira Issue
        uses: atlassian/gajira-find-issue-key@master
        with:
          string: ${{ github.head_ref }}

      - name: Update PR body
        uses: AsasInnab/pr-body-action@v1
        if: steps.find.outputs.issue != ''
        with:
          body: "[${{ steps.find.outputs.issue }}](${{ secrets.JIRA_BASE_URL }}/browse/${{ steps.find.outputs.issue }})\n${{ github.event.pull_request.body }}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}